<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Restful\Controller\SampleRestful' => 'Restful\Controller\SampleRestfulController',
            'Restful\Controller\SampleClient' => 'Restful\Controller\SampleClientController',
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
    // Uncomment below to add routes
        'routes' => array(
            'restful' => array(
                'type' => 'Literal',
                'options' => array(
                    // Change this to something specific to your module
                    'route' => '/restful',
                    'defaults' => array(
                        // Change this value to reflect the namespace in which
                        // the controllers for your module are found
                        '__NAMESPACE__' => 'Restful\Controller',
                        'controller' => 'SampleRestful',
                        //-'action' => 'index',
                    )
                ),
                'may_terminate' => true,
                'child_routes' => array(
                    //-'default' => array(
                    'client' => array(
                        'type' => 'Segment',
                        'options' => array(
                            //-'route' => '/[:controller[/:action]]',
                            'route' => '/client[/:action]',
                            'constraints' => array(
                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                //-'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                            ),
                            'defaults' => array(
                                'controller' => 'SampleClient',
                                'action' => 'index'
                            ),
                        )
                    )
                )
            )
        )
    )
);